CREATE TABLE IF NOT EXISTS user_memories (id SERIAL PRIMARY KEY, user_id INT DEFAULT 1, memory_type VARCHAR(50) DEFAULT 'user_preference', content TEXT NOT NULL, confidence FLOAT DEFAULT 0.9, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agent_shared_blackboard (id SERIAL PRIMARY KEY, entity_id VARCHAR(100) DEFAULT 'global', agent_id VARCHAR(50) NOT NULL, key VARCHAR(100) NOT NULL, value_json JSONB NOT NULL, updated_at TIMESTAMP DEFAULT NOW(), CONSTRAINT unique_agent_key UNIQUE (entity_id, key));
CREATE TABLE IF NOT EXISTS executive_action_receipts (id SERIAL PRIMARY KEY, action_type VARCHAR(50) NOT NULL, params_json JSONB, receipt_json JSONB, status VARCHAR(20) DEFAULT 'EXECUTED', executed_at TIMESTAMP DEFAULT NOW());
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS source VARCHAR(40) DEFAULT 'manual';
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS whatsapp_sender VARCHAR(80);
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS classification VARCHAR(40) DEFAULT 'new';
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS lead_score INT DEFAULT 0;
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS last_message TEXT;
ALTER TABLE clients_crm ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMP;
CREATE TABLE IF NOT EXISTS crm_whatsapp_events (id SERIAL PRIMARY KEY, sender VARCHAR(80) NOT NULL, push_name VARCHAR(160), message TEXT NOT NULL, stage VARCHAR(40) NOT NULL, classification VARCHAR(40) NOT NULL, score INT NOT NULL, lead_id INT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS chat_sessions (id VARCHAR(100) PRIMARY KEY, user_id INT DEFAULT 1, title VARCHAR(255) NOT NULL, subagent_category VARCHAR(50) DEFAULT 'central', folder VARCHAR(100) DEFAULT 'Geral', is_archived BOOLEAN DEFAULT false, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS chat_messages (id SERIAL PRIMARY KEY, session_id VARCHAR(100) NOT NULL, sender VARCHAR(50) NOT NULL, content TEXT NOT NULL, agent_name VARCHAR(100) DEFAULT 'Juliana', model_used VARCHAR(100), created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS executive_metrics (id SERIAL PRIMARY KEY, timestamp TIMESTAMP DEFAULT NOW(), session_id VARCHAR(100), model VARCHAR(100), latency_ms INT, tokens_used INT DEFAULT 0, estimated_cost_saved_usd FLOAT DEFAULT 0.05, tools_count INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS api_vault (id SERIAL PRIMARY KEY, service_name VARCHAR(100) UNIQUE NOT NULL, api_key TEXT, api_token TEXT, status VARCHAR(50) DEFAULT 'configured', updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agent_tasks (request_id VARCHAR(100) PRIMARY KEY, session_id VARCHAR(100) NOT NULL, prompt TEXT NOT NULL, state VARCHAR(20) NOT NULL DEFAULT 'queued', response TEXT, model VARCHAR(100), error TEXT, heartbeat_at TIMESTAMP DEFAULT NOW(), created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agent_task_events (id BIGSERIAL PRIMARY KEY, request_id VARCHAR(100) NOT NULL REFERENCES agent_tasks(request_id) ON DELETE CASCADE, event_type VARCHAR(40) NOT NULL, payload JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_agent_task_events_request ON agent_task_events(request_id, id);
ALTER TABLE chat_sessions ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE chat_messages ALTER COLUMN session_id TYPE VARCHAR(100);
